name: Update Stock Data

on:
  schedule:
    # 早上更新：台灣時間 09:00～13:30 (UTC 01:00～05:30)，每 30 分鐘一次
    - cron: '0 1-5 * * *'
    - cron: '30 1-5 * * *'
    # 晚上更新：台灣時間 22:30～24:00 (UTC 14:30～16:00)
    # 這行觸發 14:30 與 15:30 (UTC)
    - cron: '30 14-15 * * *'
    # 這行觸發 15:00 與 16:00 (UTC)
    - cron: '0 15-16 * * *'
  workflow_dispatch:  # 允許手動觸發

permissions:
  contents: write  # 確保 GITHUB_TOKEN 具有寫入權限

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas ta==0.10.2

      - name: Run update script
        run: |
          python scripts/update_stock_data.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update stock data [skip ci]"
          file_pattern: data/stock_data.json
          github_token: ${{ secrets.GITHUB_TOKEN }}